<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
    <AssemblyName>BoBIPet</AssemblyName>
    <Product>BoBIPet</Product>
    <Title>BoBIPet</Title>
    <Version>3.0.11</Version>
    <AssemblyVersion>3.0.11.0</AssemblyVersion>
    <FileVersion>3.0.11.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AnalysisServices.NetCore.retail.amd64" Version="19.84.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Contracts.Tests.cs" />
    <Compile Remove="HrSampleService.Tests.cs" />
  </ItemGroup>
</Project>
